site_name: 'Zespri MCS Docs'

repo_url: https://github.com/ChanningW2211/backstage
edit_uri: tree/master/ZespriMCS/docs

nav:
  - 'Introduction':
    - 'Zespri and MCS': 'https://www.qrious.co.nz/our-work/zespri'
    - 'Bitesize Introduction': './Introduction/Bitesize+Introduction.md'
    - 'Glossary': './Introduction/Glossary.md'
  - 'New project brief': 'https://sparknz.atlassian.net/wiki/spaces/UD/pages/10882876793/2023+Season+Project+Brief'
  - 'History': 
    - 'Known Problems': './History/Known+Problems.md'
    - 'Support Contract/Agreement': './History/Zespri+-+MCS+-+Support+Model+Service+Summary.md'
    - 'VIDEO - Zespri Run Through (~2hrs)': 'https://sparknz-my.sharepoint.com/personal/t825084_spark_co_nz/_layouts/15/stream.aspx?id=%2Fpersonal%2Ft825084%5Fspark%5Fco%5Fnz%2FDocuments%2FRecordings%2FZespri%20%2D%20Run%20through%2D20211207%5F133144%2DMeeting%20Recording%2Emp4&referrer=Teams%2ETEAMS%2DELECTRON&referrerScenario=p2p%5Fns%2Dbim&ga=1'
    - 'Zespri Knowledge Base (all our documentation, quite comprehensive)': './History/Zespri+Support+Knowledge+Base.md'
  - 'People': './People.md'
  - 'Technical Briefs':
    - 'Architecture diagrams': 'https://lucid.app/lucidchart/7a421fd9-73f1-4e79-88a9-49e00b39adb1/edit?viewport_loc=47%2C-107%2C1707%2C815%2C0_0&invitationId=inv_2beaa2f1-45a0-408c-b8f5-b9415b3eb41c#'
    - 'API Documentation': './Technical+Briefs/MCS+API+routes.md'
    - 'Technology Stack Overview': './Technical+Briefs/MCS+-+Technology+Stack.md'
    - 'Calc Engine Overview': './Technical+Briefs/MCS+metric+calculations+(Calc+Engine).md'

plugins:
  - techdocs-core
